// default package
// Generated 8 Aug, 2019 7:04:22 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PractId generated by hbm2java
 */
@Embeddable
public class PractId implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer age;
	private String class_;
	private String subject;
	private String passed;
	private Integer adult;

	public PractId() {
	}

	public PractId(Integer id, String name, Integer age, String class_, String subject, String passed, Integer adult) {
		this.id = id;
		this.name = name;
		this.age = age;
		this.class_ = class_;
		this.subject = subject;
		this.passed = passed;
		this.adult = adult;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 10)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "class", length = 5)
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	@Column(name = "subject", length = 15)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "passed", length = 45)
	public String getPassed() {
		return this.passed;
	}

	public void setPassed(String passed) {
		this.passed = passed;
	}

	@Column(name = "adult")
	public Integer getAdult() {
		return this.adult;
	}

	public void setAdult(Integer adult) {
		this.adult = adult;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PractId))
			return false;
		PractId castOther = (PractId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getAge() == castOther.getAge()) || (this.getAge() != null && castOther.getAge() != null
						&& this.getAge().equals(castOther.getAge())))
				&& ((this.getClass_() == castOther.getClass_()) || (this.getClass_() != null
						&& castOther.getClass_() != null && this.getClass_().equals(castOther.getClass_())))
				&& ((this.getSubject() == castOther.getSubject()) || (this.getSubject() != null
						&& castOther.getSubject() != null && this.getSubject().equals(castOther.getSubject())))
				&& ((this.getPassed() == castOther.getPassed()) || (this.getPassed() != null
						&& castOther.getPassed() != null && this.getPassed().equals(castOther.getPassed())))
				&& ((this.getAdult() == castOther.getAdult()) || (this.getAdult() != null
						&& castOther.getAdult() != null && this.getAdult().equals(castOther.getAdult())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getAge() == null ? 0 : this.getAge().hashCode());
		result = 37 * result + (getClass_() == null ? 0 : this.getClass_().hashCode());
		result = 37 * result + (getSubject() == null ? 0 : this.getSubject().hashCode());
		result = 37 * result + (getPassed() == null ? 0 : this.getPassed().hashCode());
		result = 37 * result + (getAdult() == null ? 0 : this.getAdult().hashCode());
		return result;
	}

}
