// default package
// Generated 8 Aug, 2019 7:04:22 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Pract generated by hbm2java
 */
@Entity
@Table(name = "pract", catalog = "trial")
public class Pract implements java.io.Serializable {

	private PractId id;

	public Pract() {
	}

	public Pract(PractId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "name", column = @Column(name = "name", length = 10)),
			@AttributeOverride(name = "age", column = @Column(name = "age")),
			@AttributeOverride(name = "class_", column = @Column(name = "class", length = 5)),
			@AttributeOverride(name = "subject", column = @Column(name = "subject", length = 15)),
			@AttributeOverride(name = "passed", column = @Column(name = "passed", length = 45)),
			@AttributeOverride(name = "adult", column = @Column(name = "adult")) })
	public PractId getId() {
		return this.id;
	}

	public void setId(PractId id) {
		this.id = id;
	}

}
